load("@rules_python//python:defs.bzl", "py_test")
load("@rules_rust//rust:defs.bzl", "rust_lint_config")
load("//extensions/pyo3:defs.bzl", "pyo3_extension")

rust_lint_config(
    name = "lints",
    rustc = {"unknown_lints": "allow"},
)

pyo3_extension(
    name = "string_sum",
    srcs = ["string_sum.rs"],
    edition = "2021",
    lint_config = ":lints",
)

py_test(
    name = "string_sum_test",
    srcs = ["string_sum_test.py"],
    deps = [":string_sum"],
)

pyo3_extension(
    name = "string_sum_import",
    srcs = ["string_sum_import.rs"],
    edition = "2021",
    imports = ["."],
    stubs = True,
)

py_test(
    name = "string_sum_import_test",
    srcs = ["string_sum_import_test.py"],
    deps = [":string_sum_import"],
)
